### PR TITLE
Add dns plugin

### PR DESCRIPTION
**Pull request by ghoneycutt**
This commit adds support the dns plugin as documented at
https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_dns

### CODE REVIEW

**Comment by bastelfreak** [comment]
hey @ghoneycutt could you please take a look at the failed check? Thanks for the contribution so far!

**Comment by ghoneycutt** [comment]
@bastelfreak I can't see any of the checks actually failing, just seeing a lot of style issues with the spec tests. Do I need to address the style related to the 34 offenses detected or is there something specific that is failing?

**Comment by ghoneycutt** [comment]
Interested in ensuring my commits are acceptable as I've got a few more PR's on the way.

**Comment by bastelfreak** [comment]
No direct failures, and the style checks are pretty new for us. I can't really guess how time consuming it would be to fix them and how strict we care about them. Rule of thumb is: less warnings are always better.

**Comment by danzilio** [comment]
Hey @ghoneycutt, thanks for the PR! @bastelfreak and I were just discussing this on IRC. I think we'd like to make sure the style is consistent in tests. It just makes it easier to contribute, especially for people who are new to ruby. It seems that `rubocop -a` will fix all of these for you.

**Comment by ghoneycutt** [comment]
Which network/channel ?

**Comment by danzilio** [comment]
we're in #puppet-community!

**Comment by danzilio** [comment]
on freenode! forgot that part ;)!

**Comment by danzilio** [comment]
:+1:

**Pull request merged**
