### PR TITLE
removed group naming from regex for compatibility with ruby 1.8.7

### PR DESCRIPTION
**Pull request by hdoedens**
ruby 1.8.7 does noet support regex group naming

### CODE REVIEW

**Comment by igalic** [comment]
@hdoedens thank you very much for this fix!
would you mind [squashing](https://www.git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits) your commits down to 1?

**Comment by hdoedens** [comment]
@igalic you're welcome.
Commits are squashed.

**Comment by bastelfreak** [comment]
@hdoedens here are still 5 commits, was the squash really successful? Did you maybe just forget to push?

**Comment by igalic** [comment]
@hdoedens please take a look at my https://github.com/puppet-community/puppet-jira/pull/99#issuecomment-152528108 for a how-to properly rebase / squash

**Comment by hdoedens** [comment]
I beleive the squash is succesful now. In the previous attempt I did a pull between the rebase on upstream/master and the squashing.

**Comment by igalic** [comment]
@hdoedens \o/

**Comment by hdoedens** [comment]
Thanks Igor.
I don't really care, but the company policy prevents me from collaborating publicly without prior approval.
argh! now there's 3 commits again. Should I resquash?

**Comment by bastelfreak** [comment]
hey @hdoedens could you please squash it again into one commit?

**Comment by igalic** [comment]
<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr">git is amazingly helpful<br/>
with continuous delivery<br/>
of tears</p>&mdash; The Wrath of me™ (@hirojin) <a href="https://twitter.com/hirojin/status/664023266005286912">November 10, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by hdoedens** [comment]
All should be good now. Thanx for all the help/advice!

**Comment by igalic** [comment]
/me sets :fire: to capitalism
i mean, thanks @hdoedens!

**Pull request merged**
