### PR TITLE
Add support for the AllPortsSummary option added in collectd 5.5.0.

### PR DESCRIPTION
**Pull request by dfxprima**
Collectd version 5.5.0 added the AllPortsSummary option to the tcpconns module.  This patch adds support for that option.

### CODE REVIEW

**Comment by blkperl** [comment]
Can you add a spec test?

**Comment by dfxprima** [comment]
I'll give it a try.  I've never written rspec before so it may take me while.

**Comment by blkperl** [comment]
You can look at the other plugins for examples of how to do the version check

https://github.com/pdxcat/puppet-module-collectd/blob/master/spec/classes/collectd_plugin_write_graphite_spec.rb#L96

**Comment by dfxprima** [comment]
I renamed to the summary variable to allportssummary so it matches the collectd tcpconns parameter name.  I also added the tests to validate the value of allportssummary and its inclusion in the generated file based on collectd version.

**Comment by blkperl** [comment]
Please squash your commits and rebase against master.

**Comment by dfxprima** [comment]
Please close/cancel this request.   I'll start over by putting the changes on a branch like I should have in the first place.

Thanks!

**Pull request closed without merging**
