### PR TITLE
Add rubocop syntax checking

### PR DESCRIPTION
**Pull request by blkperl**

### CODE REVIEW

**Comment by blkperl** [comment]
@daenney good idea or crazy?

**Comment by daenney** [comment]
I would totally Rubocop but for the love of god and all that is holy don't commit your Gemfile.lock.

**Comment by nibalizer** [comment]
@daenney THANK YOU @blkperl why is this so hard?

**Comment by nibalizer** [comment]
Let's use https://github.com/puppetlabs/puppet/blob/master/.rubocop.yml as our rules.

**Comment by daenney** [comment]
I agree, pick the Puppetlabs one and stay in sync with it. Means the code should have a similar look/feel and behaviour between community T&P's and stuff shipped with Puppet.

**Comment by blkperl** [comment]
@daenney ok

**Pull request closed without merging**
