### PR TITLE
Allow User and Group Settings.

### PR DESCRIPTION
**Pull request by arenstar**
Currently the user and group are hard set from params and not able to be overwritten.

In the nature of good security.. dont run anything root. :)

### CODE REVIEW

**Comment by blkperl** [comment]
Looks like something wierd happened with the python plugin. Please correct those changes and get Travis to pass.

**Comment by arenstar** [comment]
Looking good now :)

**Comment by blkperl** [comment]
Spec tests don't pass, please fix them

**Comment by arenstar** [comment]
Looking even better now :D

**Comment by blkperl** [comment]
Looks good, can you squash your 9 commits into one?

https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Pull request closed without merging**
