### PR TITLE
fix $manage_package param

### PR DESCRIPTION
**Pull request by bastelfreak**
This fixes a bug that I introduced in https://github.com/puppet-community/puppet-collectd/pull/341 (wrong variable assignment)

### CODE REVIEW

**Comment by danzilio** [comment]
:+1:

**Comment by igalic** [comment]
uh…
what was `$true` before? `undef`??
so now we're fixing the issue, but breaking backwards compatibility?

**Comment by daenney** [comment]
In a lot of plugins `$manage_package` doesn't actually do anything since they don't require external packages. In the other case it seems to only affect RHEL and what people probably did was explicitly pass in `true` or `false` because of the old broken behaviour.

I think this restores the expected behaviour so shouldn't be considered a backwards compatibility break.

**Comment by bastelfreak** [comment]
I've got the same opinion as @daenney, this will restore the expected and shouldn't break anything, but I can try to add tests later

**Comment by nibalizer** [comment]
Centos issue is known and will be fixed in #379

**Pull request merged**
