### PR TITLE
Add Plugin Filter

### PR DESCRIPTION
**Pull request by Project0**
The Chain plugin is nice, but i was missing some flexibility. 
This is a new plugin which manages the creation of the whole filter configuration. Its splitted to multiple resources to create a whole chain: chain, rule, match, target.

### CODE REVIEW

**Comment by blkperl** [comment]
Please squash your commits into 1 commit

**Comment by igalic** [comment]
@Project0 ping

**Comment by Project0** [comment]
ready to merge

**Comment by igalic** [comment]
wh00ho00 @Project0!

**Pull request merged**
